/**
 * Prompts for Giffy game
 * Players search and submit GIFs that best represent these prompts
 */

export const PROMPTS: string[] = [
  "Your reaction to seeing your crush in public",
  "How you feel when the WiFi goes down",
  "Your face when someone says 'just one more game'",
  "Trying to stay awake during a boring meeting",
  "When you finally find something you've been looking for",
  "Your reaction to getting a surprise gift",
  "How you look at 2 AM",
  "When someone eats your food from the fridge",
  "Your reaction to a cliffhanger ending",
  "Trying to understand a complicated explanation",
  "When you see your pet after a long day",
  "Your reaction to winning an argument",
  "How you feel before a job interview",
  "When you accidentally send a text to the wrong person",
  "Your reaction to a plot twist you didn't see coming",
  "Trying to act natural in an awkward situation",
  "When someone says they don't like memes",
  "Your reaction to getting a notification at 3 AM",
  "How you feel when your phone battery is at 1%",
  "When you smell something delicious in the other room",
  "Your reaction to hearing your favorite song in public",
  "Trying to open a door that says 'pull' instead of 'push'",
  "When you realize you left the oven on",
  "Your reaction to finding money in your pocket",
  "How you feel when your food delivery finally arrives",
  "When someone asks you a question right after you zoned out",
  "Your reaction to the weekend ending",
  "Trying to suppress a laugh in a serious situation",
  "When you stub your toe in the middle of the night",
  "Your reaction to seeing a dog in public",
  "How you feel when you finally fix something that was broken",
  "When you see someone wearing the same outfit as you",
  "Your reaction to getting cancelled plans",
  "Trying to explain technology to your parents",
  "When you hear your name in a crowded room",
  "Your reaction to an unexpected plot twist",
  "How you feel when you remember something embarrassing from years ago",
  "When you accidentally like an old post while stalking",
  "Your reaction to getting a perfect parking spot",
  "Trying to understand what a baby wants",
  "When you see someone trip and almost recover",
  "Your reaction to getting a surprise day off",
  "How you feel when you wake up thinking it's Monday but it's Saturday",
  "When someone says 'we need to talk'",
  "Your reaction to getting the last slice of pizza",
  "Trying to hear a conversation through a wall",
  "When you realize you've been singing out loud",
  "Your reaction to seeing a double rainbow",
  "How you feel when you sneeze and no one says bless you",
  "When you catch someone staring at you",
  "Your reaction to getting unexpected good news",
  "Trying to act cool around celebrities",
  "When you remember you have leftovers for lunch",
  "Your reaction to finding the perfect song for your mood",
  "How you feel when you finally understand a joke",
  "When you get brain freeze",
  "Your reaction to someone saying they've never seen a popular movie",
  "Trying to parallel park while people watch",
  "When you hear someone say 'literally' figuratively",
  "Your reaction to getting a compliment you don't believe",
  "How you feel when you remember a funny joke at the wrong time",
  "When you walk into a room and forget why",
  "Your reaction to finding something you thought you lost",
  "Trying to look busy when your boss walks by",
  "When someone says 'let me Google that for you'",
  "Your reaction to getting a new follower",
  "How you feel when you successfully assemble furniture",
  "When you see someone wearing socks with sandals",
  "Your reaction to getting a surprise birthday party",
  "Trying to explain your job to your grandparents",
  "When you hear your favorite movie quote in real life",
  "Your reaction to the sun coming out on a cloudy day",
  "How you feel when you beat a hard video game level",
  "When you realize you're humming without knowing it",
  "Your reaction to getting a package in the mail",
  "Trying to be polite when someone cuts you in line",
  "When someone says 'I'll do it in 5 minutes' and doesn't",
  "Your reaction to a baby smiling at you",
  "How you feel when you finally fall asleep after being awake all night",
  "When you get the perfect photo on the first try",
  "Your reaction to someone saying 'pics or it didn't happen'",
  "Trying to understand a toddler's drawing",
];

/**
 * Get a random prompt from the prompts list
 * @returns A random prompt string
 */
export function getRandomPrompt(): string {
  const randomIndex = Math.floor(Math.random() * PROMPTS.length);
  return PROMPTS[randomIndex];
}
